version: '3.8'

services:
  jenkins-blueocean:
    image: myjenkins
    ports:
      - 8080:8080
      - 50000:50000
    restart: unless-stopped
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client


volumes:
  jenkins-data:
  jenkins-docker-certs: 

    
    